name: Build Angular Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or use 20 if your Angular version supports it

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present --configuration development

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
